[project]
name = "ml-finals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.0",
    "mediapipe>=0.10.33",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pydantic>=2.13.3",
    "tensorflow>=2.21.0",
    "uvicorn>=0.45.0",
]
